# ----------------------------------------------------------------
# INTERNAL APP CONFIGURATION
# ----------------------------------------------------------------
info:
  title: Herz
  description: |-
    Extracts time series data for pressure and volume,
    synchronises these and produces a data set and plot.
settings:
  # NOTE: These units must be compatible!
  units:
    cycle: '1'
    time: 's'
    pressure: 'Pa'
    d[1,t]pressure: 'Pa/s'
    d[2,t]pressure: 'Pa/s^2'
    length: 'm'
    area: 'm^2'
    volume: 'm^3'
    d[1,t]volume: 'm^3/s'
    d[2,t]volume: 'm^3/s^2'
  # selected points in cycles for matching (alignment of multiple time series).
  matching:
    pressure: 'sys'
    volume: 'sys'
  # settings for polynomial conditions for initial (peak-to-peak) fitting.
  polynomial:
    pressure:
      - derivative: 2
        num-critical: 5
      # boundary point is peak ==> LOCAL MAX
      - derivative: 1
        time: 0.
      - derivative: 1
        time: 1.
      # boundary point of P' is inflection point
      - derivative: 2
        time: 0.
      - derivative: 2
        time: 1.
    volume:
      - derivative: 2
        num-critical: 5
      # boundary point is peak ==> LOCAL MAX
      - derivative: 1
        time: 0.
      - derivative: 1
        time: 1.
      - derivative: 2
        time: 0.
      - derivative: 2
        time: 1.
  # settings for special points
  # for marker symbols see <https://plotly.com/python/marker-style>
  points:
    pressure:
      iso-max:
        name: 'P<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
        spec: null
        marker: &marker_special
          size: 9
          colour: green
          symbol: "x"
          text: 'P<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
      sys:
        name: 'sys = P<sub>max</sub>'
        spec:
          kind: MAXIMUM
          reuse: true
          strict: false
          after: []
          before: []
        marker: &marker_sys
          size: 9
          colour: red
          symbol: "circle-open"
      es:
        name: "esp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: ['sys']
          before: []
        marker: &marker_es
          size: 9
          colour: red
          symbol: "triangle-left-open"
      anti-epad:
        name: "anti-epad"
        spec:
          derivative: 1
          kind: LOCAL-MINIMUM
          after: ['es']
          before: []
        marker: &marker_anti_epad
          size: 9
          colour: black
          symbol: "triangle-left-open"
      bd:
        name: "bdp"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: ['anti-epad']
          before: []
        marker: &marker_bd
          size: 9
          colour: blue
          symbol: "triangle-right-open"
      min:
        name: 'dia = P<sub>min</sub>'
        spec:
          kind: MINIMUM
          after: [ 'bd' ]
          before: [ 'ed' ]
        marker: &marker_dia
          size: 9
          colour: blue
          symbol: "circle-open"
      # mid:
      #   ignore: true
      #   name: "P_mid"
      #   spec:
      #     derivative: 2
      #     kind: LOCAL-MINIMUM
      #     after: [ 'min' ]
      #     before: [ 'ed' ]
      ed:
        name: "edp"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'min' ]
          before: []
        marker: &marker_ed
          size: 9
          colour: blue
          symbol: "triangle-left-open"
      epad:
        name: "epad"
        spec:
          derivative: 1
          kind: MAXIMUM
          after: [ 'edp' ]
          before: []
        marker: &marker_epad
          size: 9
          colour: black
          symbol: "triangle-right-open"
      bs:
        name: "bsp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'epad' ]
          before: []
        marker: &marker_bs
          size: 9
          colour: red
          symbol: "triangle-right-open"
    volume:
      max:
        name: 'V<sub>max</sub>'
        ignore: true
        spec:
          kind: MAXIMUM
          reuse: true
          strict: false
          after: []
          before: []
      V0:
        name: 'V<sub>0</sub>'
        spec: null
        marker:
          <<: *marker_special
          text: 'V<sub>0</sub>'
      bs:
        name: "bsv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'max' ]
          before: []
        marker:
          <<: *marker_bs
          text: ''
      sys:
        name: 'sys = V´<sub>min</sub>'
        spec:
          derivative: 1
          kind: MINIMUM
          after: [ 'bs' ]
          before: [ 'es' ]
        marker:
          <<: *marker_sys
          text: ''
      es:
        name: "esv"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'sys' ]
          before: []
        marker:
          <<: *marker_es
          text: ''
      min:
        name: 'V<sub>min</sub>'
        spec:
          kind: MINIMUM
          after: [ 'esv' ]
          before: [ 'bdv' ]
        marker:
          colour: blue
          symbol: 'square'
          size: 9
      mid:
        ignore: true
        name: "mid"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'min' ]
          before: [ 'bdv' ]
      bd:
        name: "bdv"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'min' ]
          before: [ ]
        marker:
          <<: *marker_bd
          text: ''
      dia:
        name: 'dia = V´<sub>max</sub>'
        spec:
          derivative: 1
          kind: MAXIMUM
          after: [ 'bd' ]
          before: [ 'ed' ]
        marker:
          <<: *marker_dia
          text: ''
      ed:
        name: "edv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'dia' ]
          before: [ ]
        marker:
          <<: *marker_ed
          text: ''
