# ----------------------------------------------------------------
# INTERNAL APP CONFIGURATION
# ----------------------------------------------------------------
info:
  title: Herz
  description: |-
    Extracts time series data for pressure and volume,
    synchronises these and produces a data set and plot.

settings:

  # --------------------------------
  # UNITS
  # --------------------------------
  # NOTE: must be compatible/coherent!

  units:
    cycle: "1"
    time: "s"
    frequency: "Hz"
    pressure: "Pa"
    d[1,t]pressure: "Pa/s"
    d[2,t]pressure: "Pa/s^2"
    length: "m"
    area: "m^2"
    volume: "m^3"
    d[1,t]volume: "m^3/s"
    d[2,t]volume: "m^3/s^2"
    'pressure/volume': "Pa/m^3"

  # --------------------------------
  # POINTS IN CYCLES FOR MATCHING
  # --------------------------------
  # (alignment of multiple time series).
  # matching:
  #   pressure: 'sys'
  #   volume: 'sys'
  # matching:
  #   pressure: 'bd'
  #   volume: 'anti-es'
  matching:
    pressure: 'ed'
    volume: 'ed'

  # --------------------------------
  # FOR FITTING MODELS
  # --------------------------------
  # polynomial conditions for initial (peak-to-peak) fitting.
  polynomial:
    pressure:
      - derivative: 2
        num-critical: 5
      # boundary point is peak ==> LOCAL MAX
      - derivative: 1
        time: 0.
      - derivative: 1
        time: 1.
      # boundary point of P' is inflection point
      - derivative: 2
        time: 0.
      - derivative: 2
        time: 1.

    volume:
      - derivative: 2
        num-critical: 5
      # boundary point is peak ==> LOCAL MAX
      - derivative: 1
        time: 0.
      - derivative: 1
        time: 1.
      - derivative: 2
        time: 0.
      - derivative: 2
        time: 1.

  # --------------------------------
  # SETTINGS FOR FITTING TRIG-MODEL
  # --------------------------------

  trigonometric:
    pressure:
      solver:
        n-max: 1000
        # mode: BRUTE-FORCE
        mode: HYBRID-GRADIENT
        # mode: GRADIENT
        model: DATA
        # model: POLY-MODEL
        drift: false
      points:
        a1: "P['ed'].time - T_p"
        y11: "P['ed'].value"
        b1: "P['epad'].time - T_p"
        y12: "P['epad'].value"
        a2: "P['anti-epad'].time"
        y21: "P['anti-epad'].value"
        b2: "P['bd'].time"
        y22: "P['bd'].value"
      intervals:
        - [ a1, b1 ]
        - [ a2, b2 ]
      initial:
        omega: '(omega_min + omega_max)/2'
        hshift: 'xintercept(((a1, y11), (b1, y12)), ((a2, y21), (b2, y22)))'
        # since data is normalised with L²-norm = 1, assume 2 x amplitude
        vscale: '2 * 1/math.sqrt(2)'
        # since data is shift with peak = 0
        vshift: '-1/math.sqrt(2)'
        drift: 0
      conditions:
        - kind: HSCALE-LOWER-BOUND
          value: '1*(b2 - a1)'
        - kind: HSCALE-UPPER-BOUND
          value: '2*(a2 - b1)'

  # --------------------------------
  # SETTINGS FOR FITTING EXP-MODEL
  # --------------------------------

  exponential:
    solver:
      model: DATA
      # model: POLY-MODEL
      mode: HYBRID-GRADIENT
      # mode: GRADIENT
      n-max: 1000
    points:
      # vmin: "V['anti-es'].value"
      vmin: "V['bd'].value"
      vmax: "V['ed'].value"
      # pmin: "P['bd'].value"
      pmin: "P['anti-bd'].value"
      pmax: "P['ed'].value"
    intervals:
      - [ vmin, vmax ]
    initial:
      beta: 1
      vscale: 1
      vshift: 'pmin'
    conditions:
      - kind: HSCALE-LOWER-BOUND
        value: '(vmax - vmin)/5'
      - kind: HSCALE-UPPER-BOUND
        value: '5*(vmax - vmin)'

  # --------------------------------
  # SETTINGS FOR COMPUTING SPECIAL POINTS
  # --------------------------------
  # for marker symbols see <https://plotly.com/python/marker-style>
  points:

    pressure:
      iso:
        ignore: true
        name: 'P<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
        name-simple: 'P^iso_max'
        spec: null
        format: &marker_iso
          size: 9
          colour: green
          symbol: "x"
          text: 'P<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
      sys:
        name: 'sys = P<sub>max</sub>'
        name-simple: "sys"
        spec:
          kind: MAXIMUM
          reuse: true
          strict: false
          after: []
          before: []
        format: &marker_sys
          size: 9
          colour: red
          symbol: "circle-open"
      es:
        name: "esp"
        name-simple: "esp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: ['sys']
          before: []
        format: &marker_es
          size: 9
          colour: red
          symbol: "triangle-left-open"
      anti-epad:
        name: "anti-epad"
        name-simple: "anti-epad"
        spec:
          derivative: 1
          kind: LOCAL-MINIMUM
          after: ['es']
          before: []
        format: &marker_anti_epad
          size: 9
          colour: black
          symbol: "triangle-left-open"
      bd:
        name: "bdp"
        name-simple: "bdp"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: ['anti-epad']
          before: []
        format: &marker_bd
          size: 9
          colour: blue
          symbol: "triangle-right-open"
      min:
        name: 'dia = P<sub>min</sub>'
        name-simple: "dia"
        spec:
          kind: MINIMUM
          after: [ 'bd' ]
          before: [ 'ed' ]
        format: &marker_dia
          size: 9
          colour: blue
          symbol: "circle-open"
      anti-bd:
        name: "anti-bdp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'min' ]
          before: [ 'ed' ]
        format: &marker_anti_bd
          size: 9
          colour: blue
          symbol: "triangle-left"
      ed:
        name: "edp"
        name-simple: "edp"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'min' ]
          before: []
        format: &marker_ed
          size: 9
          colour: blue
          symbol: "triangle-left-open"
      epad:
        name: "epad"
        name-simple: "epad"
        spec:
          derivative: 1
          kind: MAXIMUM
          after: [ 'ed' ]
          before: []
        format: &marker_epad
          size: 9
          colour: black
          symbol: "triangle-right-open"
      bs:
        name: "bsp"
        name-simple: "bsp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'epad' ]
          before: []
        format: &marker_bs
          size: 9
          colour: red
          symbol: "triangle-right-open"

    volume:
      iso:
        ignore: true
        name: 'V<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">min</sub>'
        name-simple: 'P^iso_max'
        spec: null
        format:
          <<: *marker_iso
          text: 'V<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">min</sub>'
      max:
        name: 'V<sub>max</sub>'
        name-simple: "V_max"
        ignore: true
        spec:
          kind: MAXIMUM
          reuse: true
          strict: false
          after: []
          before: []
      bs:
        name: "bsv"
        name-simple: "bsv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'max' ]
          before: []
        format:
          <<: *marker_bs
          text: ''
      sys:
        name: 'sys = V´<sub>min</sub>'
        name-simple: 'sys = V´_min'
        spec:
          derivative: 1
          kind: MINIMUM
          after: [ 'bs' ]
          before: [ 'es' ]
        format:
          <<: *marker_sys
          text: ''
      es:
        name: "esv"
        name-simple: "esv"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'sys' ]
          before: []
        format:
          <<: *marker_es
          text: ''
      min:
        name: 'V<sub>min</sub>'
        name-simple: "V_min"
        spec:
          kind: MINIMUM
          after: [ 'es' ]
          before: [ 'bd' ]
        format:
          colour: blue
          symbol: 'square'
          size: 9
      anti-es:
        name: "anti-esv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'min' ]
          before: [ 'bd' ]
        format:
          <<: *marker_anti_bd
          text: ''
      bd:
        name: "bdv"
        name-simple: "bdv"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'min' ]
          before: [ ]
        format:
          <<: *marker_bd
          text: ''
      dia:
        name: 'dia = V´<sub>max</sub>'
        name-simple: 'dia = V´_max'
        spec:
          derivative: 1
          kind: MAXIMUM
          after: [ 'bd' ]
          before: [ 'ed' ]
        format:
          <<: *marker_dia
          text: ''
      ed:
        name: "edv"
        name-simple: "edv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'dia' ]
          before: [ ]
        format:
          <<: *marker_ed
          text: ''

    pv:
      iso:
        name: 'P<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
        name-simple: 'P^iso_max'
        kind: PRESSURE
        format:
          <<: *marker_iso
          text-position: 'top left'

      ees:
        name: ees
        name-simple: ees
        kind: GRADIENT
        format:
          size: 1
          colour: "black"
          symbol: "dot"

      ea:
        name: ea
        name-simple: ea
        kind: GRADIENT
        format:
          size: 1
          colour: "black"
          symbol: "dot"

      eed:
        name: eed
        name-simple: eed
        kind: GRADIENT
        format:
          size: 1
          colour: "black"
          symbol: "dot"
