# ----------------------------------------------------------------
# INTERNAL APP CONFIGURATION
# ----------------------------------------------------------------
info:
  title: Loops
  description: |-
    Extracts time series data for pressure and volume,
    synchronises these and produces a data set and plot.
settings:
  units:
    cycle: '1'
    time: 's'
    pressure: 'Pa'
    d[1,t]pressure: 'Pa/s'
    d[2,t]pressure: 'Pa/s^2'
    length: 'm'
    area: 'm^2'
    volume: 'm^3'
    d[1,t]volume: 'm^3/s'
    d[2,t]volume: 'm^3/s^2'
  polynomial:
    pressure:
      degree: 10 # 2 + 7 + 1
      conditions:
        - derivative: 0
          time: 0.
        - derivative: 0
          time: 1.
        - derivative: 1
          time: 0.
        - derivative: 1
          time: 1.
        - derivative: 3
          time: 0.
        - derivative: 3
          time: 1.
    volume:
      degree: 10 # 1 + 7 + 1
      conditions:
        - derivative: 0
          time: 0.
        - derivative: 0
          time: 1.
        # - derivative: 1
        #   time: 0.
        # - derivative: 1
        #   time: 1.
        # - derivative: 2
        #   time: 0.
        # - derivative: 2
        #   time: 1.
