# ----------------------------------------------------------------
# INTERNAL APP CONFIGURATION
# ----------------------------------------------------------------
info:
  title: Loops
  description: |-
    Extracts time series data for pressure and volume,
    synchronises these and produces a data set and plot.
settings:
  units:
    cycle: '1'
    time: 's'
    pressure: 'Pa'
    d[1,t]pressure: 'Pa/s'
    d[2,t]pressure: 'Pa/s^2'
    length: 'm'
    area: 'm^2'
    volume: 'm^3'
    d[1,t]volume: 'm^3/s'
    d[2,t]volume: 'm^3/s^2'
  polynomial:
    pressure:
      # OPTIONS
      # ~~~~~~~
      # 1) Without 0 conditions on 2nd derivative,
      #    i.e. 0 conditions on 3rd derivative
      #    ==> the 2nd derivative must have >= 5 critical points
      #    ==> 3rd derivative must have >= 5 zeroes
      #    ==> polynomial must be of degree >= 3 + 5 = 8
      #
      # 2) With h (e.g. h=2) critical conditions on 2nd derivative,
      #    i.e. h conditions on 3rd derivative
      #    ==> 2nd derivative must have >= 5 + h critical points
      #    ==> 3rd derivative must have >= 5 + h zeroes
      #    ==> polynomial must be of degree >= 3 + 5 + h = 8
      degree: 8 # 3 + 5 + h [= # conditions on 3rd derivative]
      conditions:
        - derivative: 1
          time: 0.
        - derivative: 1
          time: 1.
        - derivative: 2
          time: 0.
        - derivative: 2
          time: 1.
    volume:
      degree: 7 # 2 + 5 + h [= # conditions on 2nd derivative]
      conditions:
        - derivative: 1
          time: 0.
        - derivative: 1
          time: 1.
  # settings for plotting points, see <https://plotly.com/python/marker-style>.
  markers:
    pressure:
      split:
        ignore: true
      max:
        name: "P_max"
        size: 6
        colour: red
        symbol: "circle-open"
      sys:
        name: "systolic"
        size: 6
        colour: red
        symbol: "circle"
      eivc:
        name: "eivc"
        size: 6
        colour: red
        symbol: "triangle-up-open"
      esp:
        name: "esp"
        size: 6
        colour: red
        symbol: "triangle-up"
      epad:
        name: "epad"
        size: 6
        colour: black
        symbol: "square-open"
      anti-epad:
        name: "anti-epad"
        size: 6
        colour: black
        symbol: "square"
      dia:
        name: "diastolic"
        size: 6
        colour: blue
        symbol: "x"
      sdp:
        name: "sdp"
        size: 6
        colour: blue
        symbol: "triangle-up-open"
      edp:
        name: "edp"
        size: 6
        colour: blue
        symbol: "triangle-up"
    volume:
      split:
        ignore: true
      min:
        name: "V_min"
        size: 6
        colour: blue
        symbol: "x"
      max:
        name: "V_max"
        size: 6
        colour: red
        symbol: "circle"
