# ----------------------------------------------------------------
# INTERNAL APP CONFIGURATION
# ----------------------------------------------------------------
info:
  title: Herz
  description: |-
    Extracts time series data for pressure and volume,
    synchronises these and produces a data set and plot.

settings:

  # --------------------------------
  # UNITS
  # --------------------------------
  # NOTE: must be compatible/coherent!

  units:
    cycle: "1"
    time: "s"
    frequency: "Hz"
    pressure: "Pa"
    d[1,t]pressure: "Pa/s"
    d[2,t]pressure: "Pa/s^2"
    length: "m"
    area: "m^2"
    volume: "m^3"
    d[1,t]volume: "m^3/s"
    d[2,t]volume: "m^3/s^2"
    'pressure/volume': "Pa/m^3"

  # --------------------------------
  # POINTS IN CYCLES FOR MATCHING
  # --------------------------------
  # (alignment of multiple time series).
  # NOTE: for computation of cycles + poly-fitting
  # matching:
  #   pressure: 'sys'
  #   volume: 'sys'
  # NOTE: for computation of exp-curve
  # matching: # stable
  #   pressure: 'ed'
  #   volume: 'ed'
  matching: # stable
    pressure: anti-bd
    volume: bd
  # matching: # semi-stable
  #   pressure: dia
  #   volume: anti-es
  # matching: # unstable / incorrect
  #   pressure: 'bd'
  #   volume: 'anti-es'

  # --------------------------------
  # FOR FITTING MODELS
  # --------------------------------
  # polynomial conditions for initial (peak-to-peak) fitting.
  polynomial:
    pressure:
      - derivative: 2
        num-critical: 5
      # boundary point is peak ==> LOCAL MAX
      - derivative: 1
        time: 0.
      - derivative: 1
        time: 1.
      # boundary point of P' is inflection point
      - derivative: 2
        time: 0.
      - derivative: 2
        time: 1.

    volume:
      - derivative: 2
        num-critical: 5
      # boundary point is peak ==> LOCAL MAX
      - derivative: 1
        time: 0.
      - derivative: 1
        time: 1.
      - derivative: 2
        time: 0.
      - derivative: 2
        time: 1.

  # --------------------------------
  # SETTINGS FOR FITTING TRIG-MODEL
  # --------------------------------

  trigonometric:
    pressure:
      solver: &ref_solver
        n-max: 1000
        # mode: BRUTE-FORCE
        mode: HYBRID-GRADIENT
        # mode: GRADIENT
        model: DATA
        # model: POLY-MODEL
        drift: false
      points:
        a1: "P['ed'].time - T_p"
        y11: "P['ed'].value"
        b1: "P['epad'].time - T_p"
        y12: "P['epad'].value"
        a2: "P['anti-epad'].time"
        y21: "P['anti-epad'].value"
        b2: "P['bd'].time"
        y22: "P['bd'].value"
      intervals:
        - [ a1, b1 ]
        - [ a2, b2 ]
      initial:
        omega: '(omega_min + omega_max)/2'
        hshift: 'xintercept(((a1, y11), (b1, y12)), ((a2, y21), (b2, y22)))'
        # since data is normalised with amplitude = 1, peak = 0
        vscale: 1
        vshift: -2
        drift: 0
      conditions:
        - kind: HSCALE-LOWER-BOUND
          value: '1*(b2 - a1)'
        - kind: HSCALE-UPPER-BOUND
          value: '2*(a2 - b1)'

    # volume:
    #   solver: *ref_solver
    #   points:
    #     a1: "V['anti-es'].time - T_v"
    #     y11: "V['anti-es'].value"
    #     b1: "V['bd'].time - T_v"
    #     y12: "V['bd'].value"
    #     a2: "V['sys'].time"
    #     y21: "V['sys'].value"
    #     b2: "V['es'].time"
    #     y22: "V['es'].value"
    #   intervals:
    #     - [ a1, b1 ]
    #     - [ a2, b2 ]
    #   initial:
    #     omega: '(omega_min + omega_max)/2'
    #     hshift: 'xintercept(((a1, y11), (b1, y12)), ((a2, y21), (b2, y22)))'
    #     # since data is normalised with amplitude = 1, peak = 0
    #     vscale: '1'
    #     vshift: '-2'
    #     drift: 0
    #   conditions:
    #     - kind: HSCALE-LOWER-BOUND
    #       value: '1*(b2 - a1)'
    #     - kind: HSCALE-UPPER-BOUND
    #       value: '2*(a2 - b1)'

  # --------------------------------
  # SETTINGS FOR FITTING EXP-MODEL
  # --------------------------------

  exponential:
    solver:
      model: DATA
      # model: POLY-MODEL
      # mode: HYBRID-GRADIENT
      mode: GRADIENT
      n-max: 1000

    points:
      # vmin: "V['anti-es'].value"
      vmin: "V['anti-es'].value"
      vmax: "V['ed'].value"
      tmin_v: "V['anti-es'].time - T_v"
      tmax_v: "V['ed'].time"
      # pmin: "P['bd'].value"
      pmin: "P['dia'].value"
      pmax: "P['ed'].value"
      tmin_p: "P['dia'].time - T_p"
      tmax_p: "P['ed'].time"
      # compute successively
      vmid: "V['bd'].value"
      pmid: "P['anti-bd'].value"
      pmin0: '0'           # shift P-values so that P_min = 0
      pmid0: 'pmid - pmin' # "..."
      pmax0: 'pmax - pmin' # "..."
      # analytic solution to interpolate between (vmid, pmid0) , (vmax, pmax0)
      dp: 'pmax0 - pmid0'
      dv: 'vmax - vmid'
      beta: 'math.log(1 + 2*dp/pmid0)/dv'

    initial:
      beta: 'beta'
      vscale: '(pmid0/2) * math.exp(-beta * vmid)'
      vshift: 'pmin + pmid0/2' # NOTE: have to shift by pmin to compensate

    conditions:
      - kind: INVHSCALE-LOWER-BOUND
        value: 'np.min(beta_local)'
      - kind: INVHSCALE-UPPER-BOUND
        value: 'np.max(beta_local)'

  # --------------------------------
  # SETTINGS FOR COMPUTING SPECIAL POINTS
  # --------------------------------
  # for marker symbols see <https://plotly.com/python/marker-style>
  points:

    pressure:
      iso:
        name: 'P<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
        name-simple: 'P^iso_max'
        # show only in 0th derivative in single plots
        derivatives: [0]
        # hide from 2D plot
        ignore-2D: true
        spec: null
        format: &marker_iso
          size: 9
          colour: green
          symbol: "x"
      sys:
        name: 'sys = P<sub>max</sub>'
        name-simple: "sys"
        spec:
          kind: MAXIMUM
          reuse: true
          strict: false
          after: []
          before: []
        format: &marker_sys
          size: 9
          colour: red
          symbol: "circle-open"
      es:
        name: "esp"
        name-simple: "esp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: ['sys']
          before: []
        format: &marker_es
          size: 9
          colour: red
          symbol: "triangle-left-open"
      anti-epad:
        name: "anti-epad"
        name-simple: "anti-epad"
        spec:
          derivative: 1
          kind: LOCAL-MINIMUM
          after: ['es']
          before: []
        format: &marker_anti_epad
          size: 9
          colour: black
          symbol: "triangle-left-open"
      bd:
        name: "bdp"
        name-simple: "bdp"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: ['anti-epad']
          before: []
        format: &marker_bd
          size: 9
          colour: blue
          symbol: "triangle-right-open"
      dia:
        name: 'dia = P<sub>min</sub>'
        name-simple: "dia"
        spec:
          kind: MINIMUM
          after: [ 'bd' ]
          before: [ 'ed' ]
        format: &marker_dia
          size: 9
          colour: blue
          symbol: "circle-open"
      anti-bd:
        name: "anti-bdp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'dia' ]
          before: [ 'ed' ]
        format: &marker_anti_bd
          size: 9
          colour: blue
          symbol: "triangle-left"
      ed:
        name: "edp"
        name-simple: "edp"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'dia' ]
          before: []
        format: &marker_ed
          size: 9
          colour: blue
          symbol: "triangle-left-open"
      epad:
        name: "epad"
        name-simple: "epad"
        spec:
          derivative: 1
          kind: MAXIMUM
          after: [ 'ed' ]
          before: []
        format: &marker_epad
          size: 9
          colour: black
          symbol: "triangle-right-open"
      bs:
        name: "bsp"
        name-simple: "bsp"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'epad' ]
          before: []
        format: &marker_bs
          size: 9
          colour: red
          symbol: "triangle-right-open"

    volume:
      iso:
        ignore: true
        name: 'V<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
        name-simple: 'V^iso_max'
        spec: null
        format:
          <<: *marker_iso
      max:
        name: 'V<sub>max</sub>'
        name-simple: "V_max"
        ignore: true
        spec:
          kind: MAXIMUM
          reuse: true
          strict: false
          after: []
          before: []
      bs:
        name: "bsv"
        name-simple: "bsv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'max' ]
          before: []
        format:
          <<: *marker_bs
      sys:
        name: 'sys = V´<sub>min</sub>'
        name-simple: 'sys = V´_min'
        spec:
          derivative: 1
          kind: MINIMUM
          after: [ 'bs' ]
          before: [ 'es' ]
        format:
          <<: *marker_sys
      es:
        name: "esv"
        name-simple: "esv"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'sys' ]
          before: []
        format:
          <<: *marker_es
      min:
        name: 'V<sub>min</sub>'
        name-simple: "V_min"
        spec:
          kind: MINIMUM
          after: [ 'es' ]
          before: [ 'bd' ]
        format: &marker_min
          colour: blue
          symbol: 'square'
          size: 9
      anti-es:
        name: "anti-esv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'min' ]
          before: [ 'bd' ]
        format:
          <<: *marker_anti_bd
      bd:
        name: "bdv"
        name-simple: "bdv"
        spec:
          derivative: 2
          kind: LOCAL-MAXIMUM
          after: [ 'min' ]
          before: [ ]
        format:
          <<: *marker_bd
      dia:
        name: 'dia = V´<sub>max</sub>'
        name-simple: 'dia = V´_max'
        spec:
          derivative: 1
          kind: MAXIMUM
          after: [ 'bd' ]
          before: [ 'ed' ]
        format:
          <<: *marker_dia
      ed:
        name: "edv"
        name-simple: "edv"
        spec:
          derivative: 2
          kind: LOCAL-MINIMUM
          after: [ 'dia' ]
          before: [ ]
        format:
          <<: *marker_ed

    pv:
      piso:
        name: 'P<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
        name-simple: 'P^iso_max'
        kind: PRESSURE
        format:
          <<: *marker_iso
          text-position: "top left"

      viso:
        ignore: true
        name: 'V<span style="position:relative"><sup>iso</sup><sub style="position:absolute;left:0;">max</sub>'
        name-simple: 'V^iso_max'
        kind: VOLUME
        format:
          <<: *marker_iso
          text-position: "top left"

      V0:
        visible: false # NOTE: value currently not stable
        name: 'V<sub>0</sub>'
        name-simple: 'V_0'
        kind: VOLUME
        format:
          <<: *marker_min
          text-position: "top right"

      ees:
        visible: false # NOTE: value currently not stable
        name: ees
        name-simple: ees
        kind: GRADIENT
        format:
          size: 1
          colour: "black"
          symbol: "dot"
          text-position: "middle center"

      ea:
        name: ea
        name-simple: ea
        kind: GRADIENT
        format:
          size: 1
          colour: "black"
          symbol: "dot"
          text-position: "middle center"

      eed-poly:
        name: "eed (poly)"
        name-simple: "eed (poly)"
        kind: GRADIENT
        format:
          size: 1
          colour: "black"
          symbol: "dot"
          text-position: "middle center"

      eed-exp:
        # visible: false
        name: "eed (exp)"
        name-simple: "eed (exp)"
        kind: GRADIENT
        format:
          size: 1
          colour: "black"
          symbol: "dot"
          text-position: "middle center"
