openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for user config
servers:
  - url: "https://define.me"
paths: {}
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # AppConfig
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AppConfig:
      description: |-
        Data model for all parts of the app configuration.
      type: object
      required:
        - info
        - settings
      properties:
        info:
          $ref: "#/components/schemas/AppInfo"
        settings:
          description: |-
            Primary settings
          type: object
          required:
            - units
            - polynomial
            - points
          properties:
            units:
              description: |-
                Standard units for physical conversion.
              type: object
              additionalProperties:
                type: string
                default: {}
            polynomial:
              description: |-
                Conditions for fitting (polynomial) curves to raw.
              type: object
              additionalProperties:
                $ref: "#/components/schemas/PolynomialSetting"
                default: {}
            markers:
              description: |-
                Settings for plottings special points.
              type: object
              additionalProperties:
                $ref: "#/components/schemas/MarkerSettings"
                default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Config > info
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AppInfo:
      description: |-
        Meta settings for app.
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
        version:
          type: string
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE - polynomial setting
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PolynomialSetting:
      description: |-
        Setting on for polynomial fitting for cycles within a time-series.
      type: object
      required:
        - degree
        - conditions
      properties:
        degree:
          description: |-
            Degree of polynomial to be fitted.
          type: integer
          minimum: 1
        conditions:
          description: |-
            Conditions to force on fitted polynomial
          type: array
          items:
            oneOf:
            - $ref: "#/components/schemas/PolyDerCondition"
            - $ref: "#/components/schemas/PolyIntCondition"
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE - polynomial derivative condition
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PolyDerCondition:
      description: |-
        A condition to force on fitted polynomial of the form:

        - The `n`-th derivative at time point `t` must be `0`.
      type: object
      required:
        - derivative
        - time
      properties:
        derivative:
          type: integer
          minimum: 0
        time:
          type: number
          # minimum: 0.
          # maximum: 1.
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE - polynomial integral condition
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PolyIntCondition:
      description: |-
        A condition to force on fitted polynomial of the form:

        - The integral from `t1` to `t2` must be `0`.
      type: object
      required:
        - times
      properties:
        times:
          type: array
          items:
            type: number
          minItems: 2
          maxItems: 2
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE - Points display settings
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    MarkerSettings:
      description: |-
        Settings for plotting special points.

        - `name` - <string>
        - `size` - <int> size of marker
        - `colour` - <string> colour of marker, can be either a name or of the form
            `'rgba(<float>,<float>,<float>,<float>)'`, `'hsla(<int>,<float>%,<float>%,<float>)'`, etc.
        - `symbol` - <string> symbool for marker, see <https://plotly.com/python/marker-style>.
      type: object
      required: []
      properties:
        ignore:
          type: boolean
          default: false
        name:
          type: string
          default: null
        size:
          type: integer
          default: 2
        colour:
          type: string
          default: null
        symbol:
          type: string
          default: null
      additionalProperties: false
