openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for user config
servers:
  - url: "https://define.me"
paths: {}
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # AppConfig
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AppConfig:
      description: |-
        Data model for all parts of the app configuration.
      type: object
      required:
        - info
        - settings
      properties:
        info:
          $ref: "#/components/schemas/AppInfo"
        settings:
          description: |-
            Primary settings
          type: object
          required:
            - units
            - polynomial
          properties:
            units:
              description: |-
                Standard units for physical conversion.
              type: object
              additionalProperties:
                type: string
                default: {}
            polynomial:
              description: |-
                Conditions for fitting (polynomial) curves to raw.
              type: object
              additionalProperties:
                $ref: "#/components/schemas/PolynomialSetting"
                default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Config > info
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AppInfo:
      description: |-
        Meta settings for app.
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
        version:
          type: string
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE - polynomial setting
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PolynomialSetting:
      description: |-
        Setting on for polynomial fitting for cycles within a time-series.
      type: object
      required:
        - degree
        - conditions
      properties:
        degree:
          description: |-
            Degree of polynomial to be fitted.
          type: integer
          minimum: 1
        conditions:
          description: |-
            Conditions to force on fitted polynomial
          type: array
          items:
            $ref: "#/components/schemas/PolynomialCondition"
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # DATA TYPE - polynomial condition
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PolynomialCondition:
      description: |-
        A condition to force on fitted polynomial of the form:

        - The `n`-th derivative at time point `t` (value in in `[0, 1]`)
          must be `0`.
      type: object
      required:
        - derivative
        - time
      properties:
        derivative:
          type: integer
          minimum: 0
        time:
          description: |-
            Must be a value in `[0, 1]`.
          type: number
          minimum: 0.
          maximum: 1.
      additionalProperties: false
