openapi: 3.0.3
info:
  version: x.y.z
  title: Schemata for user config
servers:
  - url: "https://define.me"
paths: {}
components:
  schemas:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # AppConfig
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AppConfig:
      description: |-
        Data model for all parts of the app configuration.
      type: object
      required:
        - info
        - settings
      properties:
        info:
          $ref: "#/components/schemas/AppInfo"
        settings:
          description: |-
            Primary settings
          type: object
          required:
            - units
          properties:
            units:
              description: |-
                Standard units for physical conversion.
              type: object
              additionalProperties:
                type: string
                default: {}
      additionalProperties: false
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Config > info
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    AppInfo:
      description: |-
        Meta settings for app.
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
        version:
          type: string
      additionalProperties: false
