name: CI Automatic
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - examples/**
      - notebooks/**
      - src/**
      - tests/**
    types:
      - assigned
      - opened
      - edited
      - reopened
      - ready_for_review
      - unlocked
      - review_requested
permissions:
  contents: read
jobs:
  job-qa:
    name: QA Pull Request
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Action - install justfile tool
        uses: extractions/setup-just@v1
        with:
          just-version: "1.14.0"
      - name: Ping - Justfile Tool
        run: |-
          just --version
      - name: Action - install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Ping - Python
        run: |-
          python3 --version
      - name: Setup - pre-installation
        run: |-
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade wheel
          python3 -m pip install --upgrade toml
      - name: Setup - build repository
        run: |-
          just build
      - name: QA - Check Linting
        run: |-
          just check-linting
      - name: QA - Unit Tests
        run: |-
          just tests-logs
