name: CI
on:
  workflow_dispatch:
    inputs:
      docker-image:
        description: Choice of docker image on which to run action.
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          # - macos-latest
          # - macos-latest-xl
          # - macos-13
          # - macos-13-xl
      log-level:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  pull_request:
    branches:
      - main
      - dev
    paths:
      - examples/**
      - notebooks/**
      - src/**
      - tests/**
    types:
      - assigned
      - opened
      - edited
      - reopened
      - ready_for_review
      - unlocked
      - review_requested
permissions:
  contents: read
jobs:
  job-qa-dispatch:
    name: QA Manual
    # runs-on: [self-hosted, "${{ github.event.inputs.os }}", x64, gpu]
    runs-on: ${{ github.event.inputs.docker-image }}
    steps:
      - uses: actions/checkout@v3
      - name: Action - install justfile tool
        uses: extractions/setup-just@v1
        with:
          just-version: "1.14.0"
      - name: Ping - Justfile Tool
        run: |-
          just --version
      - name: Action - install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Ping - Python
        run: |-
          python3 --version
      - name: Setup - pre-installation
        run: |-
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade wheel
          python3 -m pip install --upgrade toml
      - name: Setup - build repository
        run: |-
          just build
      - name: QA - Check Linting
        run: |-
          just check-linting
      - name: QA - Unit Tests
        run: |-
          just tests-logs
  job-qa-pr:
    name: QA Pull Request
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Action - install justfile tool
        uses: extractions/setup-just@v1
        with:
          just-version: "1.14.0"
      - name: Ping - Justfile Tool
        run: |-
          just --version
      - name: Action - install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Ping - Python
        run: |-
          python3 --version
      - name: Setup - pre-installation
        run: |-
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade wheel
          python3 -m pip install --upgrade toml
      - name: Setup - build repository
        run: |-
          just build
      - name: QA - Check Linting
        run: |-
          just check-linting
      - name: QA - Unit Tests
        run: |-
          just tests-logs
