name: CI
on:
  workflow_dispatch:
    inputs:
      docker-image:
        description: Choice of docker image on which to run action.
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - macos-latest-xl
          - macos-13
          - macos-13-xl
      log-level:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
permissions:
  contents: read
jobs:
  build:
    # runs-on: [self-hosted, "${{ github.event.inputs.os }}", x64, gpu]
    runs-on: ${{ github.event.inputs.docker-image }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Ping
        run: |-
          python3 --version
