openapi: 3.0.3
info:
  version: 0.1.1
  title: Schemata for user configuration.
servers:
  - url: "https://define.me"
paths: {}
components:
  schemas:
    # ----------------------------------------------------------------
    # CLASSES
    # ----------------------------------------------------------------

    # --------------------------------
    # RequestsConfig
    # --------------------------------
    RequestsConfig:
      description: |-
        Data model for all parts of the user configuration.
      type: object
      required: []
      properties:
        requests:
          description: |-
            List of settings for each case.
          type: array
          items:
            $ref: "#/components/schemas/RequestConfig"
          default: []
      additionalProperties: true

    # --------------------------------
    # Config > case(s)
    # --------------------------------
    RequestConfig:
      description: |-
        User settings for a single case of data.
      type: object
      required:
        - endpoint
        - label
        - name
        - data
        - process
        - output
      properties:
        ignore:
          description: |-
            Whether or not to skip the case.
          type: boolean
          default: false
        endpoint:
          $ref: "#/components/schemas/EnumEndpoint"
        label:
          description: |-
            Label used to refer to case and generate output files.
            NOTE: may not contain spaces.
          type: string
          pattern: '^\S+$'
        name:
          description: |-
            Name of case (can be used e.g. in titles of plots).
          type: string
        data:
          $ref: "#/components/schemas/UserData"
        process:
          $ref: "#/components/schemas/UserProcess"
        output:
          $ref: "#/components/schemas/UserOutput"
      additionalProperties: false

    # --------------------------------
    # Config > case > data
    # --------------------------------
    UserData:
      description: |-
        Options for structure of data files.
      type: object
      required:
        - pressure
        - volume
      properties:
        pressure:
          $ref: "#/components/schemas/DataTimeSeries"
        volume:
          $ref: "#/components/schemas/DataTimeSeries"
      additionalProperties: false

    # --------------------------------
    # Config > case > process
    # --------------------------------
    UserProcess:
      description: |-
        Options for process steps.
      type: object
      required:
        - combine
        - cycles
        - fit
      properties:
        combine:
          description: |-
            Parameter options for combining time series.
          type: object
          required:
            - dt
            - unit
          properties:
            dt:
              type: number
              minimum: 0.
              exclusiveMinimum: true
            T-max:
              type: number
              minimum: 0.
              exclusiveMinimum: true
            unit:
              type: string
          additionalProperties: true
        cycles:
          type: object
          required: []
          properties:
            remove-bad:
              description: |-
                Option to remove 'bad' parts at start/end of cycles.
              type: boolean
              default: false
          additionalProperties: true
        fit:
          type: object
          required: []
          properties:
            mode:
              description: |-
                Whether to fit for each cycle individually,
                or to fit for all simultaneously (average).
              $ref: "#/components/schemas/EnumFittingMode"
              default: AVERAGE
          additionalProperties: true
      additionalProperties: true

    # --------------------------------
    # Config > case > output
    # --------------------------------
    UserOutput:
      description: |-
        Options for outputs
      type: object
      required:
        - quantities
        - table
        - plot
      properties:
        name:
          description: |-
            Name of case.
          type: string
        quantities:
          description: |-
            User settings for output quantities.
          type: array
          items:
            $ref: '#/components/schemas/DataTypeColumn'
          minItems: 1
        table:
          type: object
          required:
            # - path
            - sep
            - decimal
          properties:
            path:
              $ref: "./common.yaml/#/components/schemas/PathToDirString"
            sep:
              type: string
              default: ";"
            decimal:
              type: string
              default: "."
          additionalProperties: true
        plot:
          type: object
          required:
            # - path
            - font
          properties:
            path:
              $ref: "./common.yaml/#/components/schemas/PathToDirString"
            legend:
              type: boolean
              default: false
            font:
              type: object
              required: []
              properties:
                family:
                  type: string
                  default: 'Tahoma'
                size:
                  description: |-
                    Size of font (in entire plot) in `pt`.
                  type: integer
                  default: 12
                size-title:
                  description: |-
                    Size of title font in `pt`.
                  type: integer
                  default: 14
                size-legend:
                  description: |-
                    Size of legend font in `pt`.
                  type: integer
                  default: 10
              additionalProperties: false
          additionalProperties: true
      additionalProperties: true

    # --------------------------------
    # Data structure for time series
    # --------------------------------
    DataTimeSeries:
      description: |-
        Structure for time series.
      type: object
      required:
        - path
        - time
        - value
      properties:
        # path to file
        path:
          description: |-
            Path to file containing time series.
          $ref: "./common.yaml/#/components/schemas/PathToDirString"
        # special settings
        sep:
          description: |-
            Delimiter for columns used in file.
          type: string
          default: ';'
        decimal:
          description: |-
            Symbol for decimals used in file.
          type: string
          default: '.'
        skip:
          description: |-
            Which row indexes to skip.
            Either provide

            - a string of a lambda function (mapping integers to boolean values)
            - an integer, indicating how many rows to skip from the top
            - an array

            Noted that row numbers are **0-based**!
          oneOf:
            - type: integer
            - type: array
              items:
                type: integer
            - type: string
          examples:
            simple:
              value: 3
              summary: Rows `0,1,2` will be skipped.
            function:
              value: "`lambda i: i % 3 == 1`"
              summary: |-
                Skips every 3rd rwo starting from row-index 1
            array:
              value: [0, 1, 2, 4, 5]
              summary: |-
                In this case in the file
                - extra headers are on lines `0, 1, 2``,
                - headers are on row `3`
                - rows 4 and 5 contain further skippable content

                NOTE: negative values will be ignored.
          default: []
        # columns
        time:
          description: |-
            Column name for time.
          $ref: "#/components/schemas/DataTypeQuantity"
        value:
          description: |-
            Column name for value.
          $ref: "#/components/schemas/DataTypeQuantity"
      additionalProperties: false

    DataTypeQuantity:
      description: |-
        Structure for physical quantity as column
      type: object
      required:
        - name
        - unit
        # - type
      properties:
        name:
          description: |-
            Name of column in file.
        type:
          description: |-
            Data type (float, int, etc.)
          $ref: "./common.yaml/#/components/schemas/EnumType"
          default: float
        unit:
          description: |-
            Physical unit as string
          type: string
      additionalProperties: false

    DataTypeColumn:
      description: |-
        Structure for physical quantity for outputs.
      type: object
      required:
        - name
        - quantity
        - key
        - unit
        # - type
      properties:
        ignore:
          description: |-
            If `ignore = false`, then column will be included in combined output.
            Otherwise just used for internal computations.
          type: boolean
          default: false
        name:
          description: |-
            Desired name of column in file.
          type: string
        quantity:
          description: |-
            (Root) name of physical quantity.
            E.g. for a column for "fitted pressure"
            use `quantity="pressure"`.
          type: string
        key:
          description: |-
            Name of column in internal data frame.
            E.g. for a column for "fitted pressure"
            use `key="pressure[fit]"`.
          type: string
        type:
          description: |-
            Data type (float, int, etc.)
          $ref: "./common.yaml/#/components/schemas/EnumType"
          default: float
        unit:
          description: |-
            Physical unit as string
          type: string
      additionalProperties: false

    # ----------------------------------------------------------------
    # ENUMS
    # ----------------------------------------------------------------

    # --------------------------------
    # ENUM: Programme Mode
    # --------------------------------
    EnumProgrammeMode:
      description: |-
        Enumeration of endpoints for executing main programme.
      type: string
      enum:
        - version
        - requests
      default: version

    # --------------------------------
    # ENUM: Endpoint
    # --------------------------------
    EnumEndpoint:
      description: |-
        Enumeration of endpoints for requests
      type: string
      enum:
        - UNKNOWN
        - RIGHT-VENTRICLE
      default: version

    # --------------------------------
    # ENUM: fitting mode
    # --------------------------------
    EnumFittingMode:
      description: |-
        Enumeration of settings for log level.
      type: string
      enum:
        - SINGLE
        - AVERAGE
      default: AVERAGE
